const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const companySchema = new Schema({
    // Company id by default is auto-generated by MongoDB
    company_name : {
        type : String,
        required: true,
        trim: true
    },
    company_logo : {
        type: String,
        trim: true,
    }
}, {timestamps: true});

const Company = mongoose.model('Company', companySchema);
module.exports = Company;