const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const documentSchema = new Schema({
    // Document id by default is auto-generated by MongoDB
    ipo_id: {
        type: Schema.Types.ObjectId,
        ref: 'IPO',
        required: true
    },
    rhp_pdf: String,    // Red Herring Prospectus PDF URL
    drhp_pdf: String,   // Draft Red Herring Prospectus PDF URL
}, { timestamps: true });

const Document = mongoose.model('Document', documentSchema);
module.exports = Document;