const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const ipoSchema = new Schema({
    // IPO id by default is auto-generated by MongoDB
    company_id: {
        type: Schema.Types.ObjectId,
        ref: 'Company',
    },
    price_band: String, 
    open_date: Date,
    close_date: Date, 
    issue_size: String, 
    issue_type: String, 
    listing_date: {
        type: Date,
        default: Date.now
    }, 
    status: {
        type: String,
        enum: ['Upcoming', 'Open', 'Closed', 'Listed'],
        default: 'Upcoming'
    },
    ipo_price: Number, 
    listing_price: Number, 
    listing_gain: Number, 
    current_market_price: Number, 
    current_return: Number,
}, { timestamps: true });

const IPO = mongoose.model('IPO', ipoSchema);
module.exports = IPO;